use crate::{
    alchemy::Element,
    planet::Planet,
    tree_of_life::{Column, Realm},
};

use super::{Node, Sefira};

pub fn create_nodes() -> Vec<Node> {
    vec![
        Node::new(
            Sefira::Keter,
            "Crown".to_string(),
            Planet::Pluto,
            Column::Balance,
            Realm::Atziluth,
            1,
        ),
        Node::new(
            Sefira::Chokmah,
            "Wisdom".to_string(),
            Planet::Neptune,
            Column::Mercy,
            Realm::Atziluth,
            2,
        ),
        Node::new(
            Sefira::Binah,
            "Understanding".to_string(),
            Planet::Saturn,
            Column::Severity,
            Realm::Atziluth,
            3,
        ),
        Node::new(
            Sefira::Chesed,
            "Mercy".to_string(),
            Planet::Jupiter,
            Column::Mercy,
            Realm::Beriah,
            4,
        ),
        Node::new(
            Sefira::Gevurah,
            "Strength".to_string(),
            Planet::Mars,
            Column::Severity,
            Realm::Beriah,
            5,
        ),
        Node::new(
            Sefira::Tiferet,
            "Beauty".to_string(),
            Planet::Sun,
            Column::Balance,
            Realm::Beriah,
            6,
        ),
        Node::new(
            Sefira::Netsach,
            "Victory".to_string(),
            Planet::Venus,
            Column::Mercy,
            Realm::Yetzirah,
            7,
        ),
        Node::new(
            Sefira::Hod,
            "Splendor".to_string(),
            Planet::Mercury,
            Column::Severity,
            Realm::Yetzirah,
            8,
        ),
        Node::new(
            Sefira::Yesod,
            "Foundation".to_string(),
            Planet::Moon,
            Column::Balance,
            Realm::Yetzirah,
            9,
        ),
        Node::new(
            Sefira::Malkuth,
            "Kingdom".to_string(),
            Planet::Earth,
            Column::Balance,
            Realm::Assiah,
            10,
        ),
    ]
}
